### ISSUE TITLE
gen/curve: p256 performance differences

### ISSUE THREAD

**Issue by mmcloughlin** [mmcloughlin/ec3#92]
Current version significantly underperforms the standard library version. We need to understand the differences and make up the gap.

```
$ go test -run NONE -benchtime 10s -bench ScalarMult -cpuprofile cpu.out -memprofile mem.out ./examples/p256/
goos: darwin
goarch: amd64
pkg: github.com/mmcloughlin/ec3/examples/p256
BenchmarkScalarMult-4      	  105849	    115714 ns/op
BenchmarkStdScalarMult-4   	  191718	     56123 ns/op
PASS
ok  	github.com/mmcloughlin/ec3/examples/p256	25.013s
```

Our generated code:

<img width="100%" alt="Screen Shot 2019-09-16 at 12 47 56 PM" src="https://user-images.githubusercontent.com/7133685/64988408-436ad880-d880-11e9-86b3-d6ceb256d9d6.png">

`crypto/elliptic.P256`:

<img width="100%" alt="Screen Shot 2019-09-16 at 12 47 44 PM" src="https://user-images.githubusercontent.com/7133685/64988420-48c82300-d880-11e9-9ea6-f8f153d334f9.png">

Optimizations that should help:

- [ ] Addition and doubling formulae directly in assembly rather than Go calling into assembly #93 
- [x] Lookup table selection in assembly #94 
- [ ] Specific square implementation #34 
- [ ] Exploit structure of prime in montgomery reduction #95 

Related #55
